eth-web3-providers: {{ "https://mainnet.infura.io/v3/66fcca4d964d460c9f2064bdbef3d6e6" | b64enc }}
bsc-web3-providers: {{"https://bsc-dataseed.binance.org/,https://bsc-dataseed1.defibit.io/,https://bsc-dataseed1.ninicoin.io/" | b64enc}}
avalanche-web3-providers: {{"https://api.avax.network/ext/bc/C/rpc" | b64enc}}
polygon-web3-providers: {{"https://rpc-mainnet.matic.network" | b64enc}}
aurora-web3-providers: {{"https://mainnet.aurora.dev" | b64enc}}
aws-access-key-id: {{ "" | b64enc }}
aws-secret-key: {{ "" | b64enc }}
neo4j-username: {{ "neo4j" | b64enc }}
neo4j-password: {{ "" | b64enc }}
loggly-token: {{ "" | b64enc }}
loggly-subdomain: {{ "hotcross" | b64enc }}
redis-password: {{ "" | b64enc }}
priv-key: {{ "" | b64enc}}
kyc-priv-key: {{ "" | b64enc}}
synapse-client-id: {{ "" | b64enc}}
synapse-api-key: {{ "" | b64enc}}
gh-token: {{ "" | b64enc }}
unmarshal-auth-key: {{ "" | b64enc }}
