apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: neo4j-backup
  namespace: indexer
spec:
  schedule: "0 0 * * *" # at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: hotcross
          containers:
            - name: neo4j-backup
              image: registry.digitalocean.com/hotcross/neo4j-backup:4.2.7
              env:
              - name: DB_NAME
                value: neo4j
              - name: BUCKET
                value: gs://er-neo4j-backups
              - name: BACKUP_NAME
                value: db-backup
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /auth/credentials.json
              volumeMounts:
              - name: creds
                mountPath: /auth
                readOnly: true
              command:
                - "/bin/bash"
                - "-c"
                - |
                  export NEO4J_ADDR=neo4j-neo4j.indexer.svc.cluster.local:6362

                  exec /scripts/backup.sh
          volumes:
          - name: creds
            secret:
              secretName: neo4j-backup-sa
              items:
              - key: credentials.json
                path: credentials.json
