apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: crossvesting
  namespace: crossvesting
spec:
  rules:
  - host: vest.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-vesting
            port:
              number: 80
  tls:
  - hosts:
    - vest.hotcross.dev
    secretName: hotcross-tls
