apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: crossbridge
  namespace: crossbridge
spec:
  rules:
  - host: bridge.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-bridge-dapp
            port:
              number: 80
  tls:
  - hosts:
    - bridge.hotcross.dev
    secretName: hotcross-tls-crossbridge
