apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: crosspool
  namespace: crosspool
spec:
  rules:
  - host: app.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: cross-pool
            port:
              number: 80
  tls:
  - hosts:
    - app.hotcross.dev
    secretName: hotcross-tls
