apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: crosspool2
  namespace: crosspool
spec:
  rules:
  - host: crosspool2.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-pool-2
            port:
              number: 80
  tls:
  - hosts:
    - crosspool2.hotcross.dev
    secretName: hotcross-tls-2
