apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: hotvip
  namespace: crosspool
spec:
  rules:
  - host: hotvip.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hotvip
            port:
              number: 80
  tls:
  - hosts:
    - hotvip.hotcross.dev
    secretName: hotcross-tls-vip
