apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: ipfs
  namespace: bttc
spec:
  rules:
  - host: ipfs.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ipfs
            port:
              number: 5001
  - host: ipfs-api.hotcross.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ipfs
            port:
              number: 8080
  tls:
  - hosts:
    - ipfs.hotcross.dev
    - ipfs-api.hotcross.dev
    secretName: hotcross-ipfs-tls
