apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/limit-connections: '10'
    # nginx.ingress.kubernetes.io/limit-rpm: '60'
    # nginx.ingress.kubernetes.io/upstream-hash-by: $remote_addr
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: api
  namespace: api
spec:
  rules:
  - host: api.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-api
            port:
              number: 80
  tls:
  - hosts:
    - api.hotcross.com
    secretName: hotcross-tls
