apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/temporal-redirect: https://app.hotcross.com/pools
  name: crosspoollegacy
  namespace: hotcross
spec:
  rules:
  - host: crosspool.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-svc
            port:
              number: 80
  tls:
  - hosts:
    - crosspool.hotcross.com
    secretName: cross-pool-legacy-tls
