apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-connections: '5'
    nginx.ingress.kubernetes.io/limit-rpm: '60'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: crossbridge
  namespace: crossbridge
spec:
  rules:
  - host: app.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: /bridge(/|$)(.*)
        backend:
          service:
            name: cross-bridge-dapp
            port:
              number: 80
  tls:
  - hosts:
    - app.hotcross.com
    secretName: hotcross-tls
