apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-connections: '5'
    nginx.ingress.kubernetes.io/limit-rpm: '60'
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: crossvest
  namespace: crossvest
spec:
  rules:
  - host: vest.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-vest-admin
            port:
              number: 80
  - host: claim.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-vest-investor
            port:
              number: 80
  tls:
  - hosts:
    - vest.hotcross.com
    - claim.hotcross.com
    secretName: hotcross-tls
