apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: crosspoolsecret
  namespace: crosspool
spec:
  rules:
  - host: x4ukfslubv2krw.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cross-pool
            port:
              number: 80
  tls:
  - hosts:
    - x4ukfslubv2krw.hotcross.com
    secretName: hotcross-secret-tls
