apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: crosssend
  namespace: crosssend
spec:
  rules:
  - host: app.hotcross.com
    http:
      paths:
      - pathType: Prefix
        path: /send(/|$)(.*)
        backend:
          service:
            name: cross-send
            port:
              number: 80
  tls:
  - hosts:
    - app.hotcross.com
    secretName: hotcross-tls
