apiVersion: v1
kind: Service
metadata:
  name: {{ include "hotcross.fullname" . }}
  labels:
    {{- include "hotcross.labels" . | nindent 4 }}
  namespace: {{ .Values.ns }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hotcross.selectorLabels" . | nindent 4 }}
