apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-2
    # - port: 4001
    #   targetPort: 4001
    #   protocol: TCP
    #   name: http-3
    # - port: 4001
    #   targetPort: 4001
    #   protocol: UDP
    #   name: udp
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
