apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graph-node.secrets.fullname" . }}
  namespace: {{ .Values.ns }}
  labels:
    app.kubernetes.io/name: {{ template "graph-node.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
type: Opaque
data:
{{- if eq .Values.env "staging" }}
{{ tpl (.Files.Get (printf "conf/%s/secrets.staging.yaml" .Values.nameOverride)) . | indent 2 }}
{{- else if eq .Values.env "production" }}
{{ tpl (.Files.Get (printf "conf/%s/secrets.prod.yaml" .Values.nameOverride) ) . | indent 2 }}
{{- end }}
