apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
  namespace: {{ .Values.ns }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: graphql-http
      protocol: TCP
      name: graphql-http
    - port: 8001
      targetPort: graphql-ws
      protocol: TCP
      name: graphql-ws
    - port: 8020
      targetPort: json-rpc
      protocol: TCP
      name: json-rpc
    - port: 8030
      targetPort: subgraph-status
      protocol: TCP
      name: subgraph-status
  selector:
    {{- include "graph-node.selectorLabels" . | nindent 4 }}
