---
apiVersion: v1
kind: Namespace
metadata:
  name: crosspool
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossbridge
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: Namespace
metadata:
  name: indexer
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossmint
