apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cross-bridge-validator.secrets.fullname" . }}
  namespace: {{ .Values.ns }}
  labels:
    app.kubernetes.io/name: {{ template "cross-bridge-validator.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
type: Opaque
data:
{{- if eq .Values.env "staging" }}
{{ tpl (.Files.Get "conf/secrets.staging.yaml") . | indent 2 }}
{{- else if eq .Values.env "production" }}
{{tpl (.Files.Get "conf/secrets.prod.yaml") . | indent 2 }}
{{- end }}
