apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cross-api.fullname" . }}
  labels:
    {{- include "cross-api.labels" . | nindent 4 }}
  namespace: {{ .Values.ns }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cross-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "cross-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cross-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- if eq .Values.env "staging" }}
{{tpl (.Files.Get "conf/env.staging.yaml") . | indent 12 }}
{{- else if eq .Values.env "production" }}
{{tpl (.Files.Get "conf/env.prod.yaml") . | indent 12 }}
{{- end }}
            - name: ETH_WEB3_PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: eth-web3-providers
            - name: BSC_WEB3_PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: bsc-web3-providers
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: aws-access-key-id
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: aws-secret-key
            - name: LOGGLY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: loggly-token
            - name: LOGGLY_SUBDOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: loggly-subdomain
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: redis-password
            - name: NEO4J_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: neo4j-username
            - name: NEO4J_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: neo4j-password
            - name: KYC_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "cross-api.secrets.fullname" . }}
                  key: kyc-priv-key
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
