apiVersion: v1
kind: Service
metadata:
  name: {{ include "cross-api.fullname" . }}
  labels:
    {{- include "cross-api.labels" . | nindent 4 }}
  namespace: {{ .Values.ns }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-hostname: "api.hotcross.com"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cross-api.selectorLabels" . | nindent 4 }}
